### ISSUE TITLE
not a issue but if you use javascript: then enter what code you want does that work

### ISSUE THREAD

**Issue by VybzOnWii** [DarkSnakeGang/GoogleSnakeAnimatedColours#1]

**Comment by hwatson381** [comment]
The mod is broken at the moment, but I've got plans to release an improved version over the next few weeks. I think using 'javascript:' in the address bar would've worked before it broke, but the improved version will have a GUI instead for selecting the pattern/background pattern.

**Comment by VybzOnWii** [comment]
ok

**Comment by hwatson381** [comment]
It's fixed now. People may need to redownload the latest version.
